-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema chabit
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema chabit
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chabit` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `chabit` ;

-- -----------------------------------------------------
-- Table `chabit`.`CATEGORY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chabit`.`CATEGORY` ;

CREATE TABLE IF NOT EXISTS `chabit`.`CATEGORY` (
  `CATEGORY_ID` BIGINT NOT NULL,
  `CATEGORY_NAME` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`CATEGORY_ID`),
  UNIQUE INDEX `CATEGORY_NAME_UNIQUE` (`CATEGORY_NAME` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chabit`.`USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chabit`.`USER` ;

CREATE TABLE IF NOT EXISTS `chabit`.`USER` (
  `USER_ID` BIGINT NOT NULL,
  `USER_EMAIL` VARCHAR(255) NOT NULL,
  `USER_PASSWORD` VARCHAR(50) NOT NULL,
  `USER_PHONE` VARCHAR(50) NULL DEFAULT NULL,
  `USER_POINTS` INT NULL DEFAULT '1000',
  `USER_ROLE` VARCHAR(45) NOT NULL DEFAULT 'USER',
  `USER_JOINDATE` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `USER_NAME` VARCHAR(45) NULL,
  `USER_NICKNAME` VARCHAR(45) NULL,
  `USER_IMAGE` TEXT NULL,
  PRIMARY KEY (`USER_ID`),
  UNIQUE INDEX `USER_EMAIL_UNIQUE` (`USER_EMAIL` ASC) VISIBLE,
  UNIQUE INDEX `USER_NICKNAME_UNIQUE` (`USER_NICKNAME` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chabit`.`CHALLENGE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chabit`.`CHALLENGE` ;

CREATE TABLE IF NOT EXISTS `chabit`.`CHALLENGE` (
  `CHALLENGE_ID` BIGINT NOT NULL,
  `CHALLENGE_NAME` VARCHAR(255) NOT NULL,
  `CHALLENGE_DESC` TEXT NULL DEFAULT NULL,
  `CHALLENGE_OWNER` BIGINT NOT NULL,
  `CHALLENGE_CATEGORY` BIGINT NULL DEFAULT NULL,
  `CHALLENGE_STARTDATE` DATETIME NOT NULL,
  `CHALLENGE_ENDDATE` DATETIME NOT NULL,
  `CHALLENGE_THUMBNAIL` TEXT NULL DEFAULT NULL,
  `CHALLENGE_POINT` INT NULL DEFAULT '100',
  `CHALLENGE_USERCOUNT` INT NULL DEFAULT '1',
  `AUTH_WAY` VARCHAR(255) NULL DEFAULT NULL,
  `AUTH_FREQUENCY` VARCHAR(255) NOT NULL,
  `AUTH_STARTTIME` TIME NULL DEFAULT '00:00:00',
  `AUTH_ENDTIME` TIME NULL DEFAULT '23:59:59',
  `AUTH_HOLIDAY` TINYINT NOT NULL,
  `AUTH_EXAMPLE` TEXT NULL DEFAULT NULL,
  `CHALLENGE_ONGOING` VARCHAR(45) NULL DEFAULT 'READY',
  PRIMARY KEY (`CHALLENGE_ID`),
  INDEX `CHALLENGE_USER_FK_idx` (`CHALLENGE_OWNER` ASC) VISIBLE,
  INDEX `CHALLENGE_CATEGORY_FK_idx` (`CHALLENGE_CATEGORY` ASC) VISIBLE,
  CONSTRAINT `CHALLENGE_CATEGORY_FK`
    FOREIGN KEY (`CHALLENGE_CATEGORY`)
    REFERENCES `chabit`.`CATEGORY` (`CATEGORY_ID`),
  CONSTRAINT `CHALLENGE_USER_FK`
    FOREIGN KEY (`CHALLENGE_OWNER`)
    REFERENCES `chabit`.`USER` (`USER_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chabit`.`HASHTAG`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chabit`.`HASHTAG` ;

CREATE TABLE IF NOT EXISTS `chabit`.`HASHTAG` (
  `HASHTAG_ID` BIGINT NOT NULL,
  `HASHTAG_NAME` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`HASHTAG_ID`),
  UNIQUE INDEX `HASHTAG_NAME_UNIQUE` (`HASHTAG_NAME` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chabit`.`CHALLENGE_HASHTAG`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chabit`.`CHALLENGE_HASHTAG` ;

CREATE TABLE IF NOT EXISTS `chabit`.`CHALLENGE_HASHTAG` (
  `CHALLENGE_ID` BIGINT NOT NULL,
  `HASHTAG_ID` BIGINT NOT NULL,
  INDEX `CHALLENGE_HASHTAG_CHALLENGE_FK_idx` (`CHALLENGE_ID` ASC) VISIBLE,
  INDEX `CHALLENGE_HASHTAG_HASHTAG_FK_idx` (`HASHTAG_ID` ASC) VISIBLE,
  PRIMARY KEY (`CHALLENGE_ID`, `HASHTAG_ID`),
  CONSTRAINT `CHALLENGE_HASHTAG_CHALLENGE_FK`
    FOREIGN KEY (`CHALLENGE_ID`)
    REFERENCES `chabit`.`CHALLENGE` (`CHALLENGE_ID`),
  CONSTRAINT `CHALLENGE_HASHTAG_HASHTAG_FK`
    FOREIGN KEY (`HASHTAG_ID`)
    REFERENCES `chabit`.`HASHTAG` (`HASHTAG_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chabit`.`REVIEW`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chabit`.`REVIEW` ;

CREATE TABLE IF NOT EXISTS `chabit`.`REVIEW` (
  `REVIEW_ID` BIGINT NOT NULL,
  `REVIEW_CONTENT` TEXT NOT NULL,
  `REVIEW_DATE` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `COOL_COUNT` INT NULL DEFAULT '0',
  `COMMENT_COUNT` INT NULL DEFAULT '0',
  `USER_ID` BIGINT NULL DEFAULT NULL,
  `CHALLENGE_ID` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`REVIEW_ID`),
  INDEX `REVIEW_USER_FK_idx` (`USER_ID` ASC) VISIBLE,
  INDEX `REVIEW_CHALLENGE_FK_idx` (`CHALLENGE_ID` ASC) VISIBLE,
  CONSTRAINT `REVIEW_CHALLENGE_FK`
    FOREIGN KEY (`CHALLENGE_ID`)
    REFERENCES `chabit`.`CHALLENGE` (`CHALLENGE_ID`),
  CONSTRAINT `REVIEW_USER_FK`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `chabit`.`USER` (`USER_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chabit`.`COOL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chabit`.`COOL` ;

CREATE TABLE IF NOT EXISTS `chabit`.`COOL` (
  `COOL_ID` BIGINT NOT NULL,
  `REVIEW_ID` BIGINT NULL DEFAULT NULL,
  `USER_ID` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`COOL_ID`),
  INDEX `COOL_REVIEW_FK_idx` (`REVIEW_ID` ASC) VISIBLE,
  INDEX `COOL_USER_FK_idx` (`USER_ID` ASC) VISIBLE,
  CONSTRAINT `COOL_REVIEW_FK`
    FOREIGN KEY (`REVIEW_ID`)
    REFERENCES `chabit`.`REVIEW` (`REVIEW_ID`),
  CONSTRAINT `COOL_USER_FK`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `chabit`.`USER` (`USER_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chabit`.`FOLLOW`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chabit`.`FOLLOW` ;

CREATE TABLE IF NOT EXISTS `chabit`.`FOLLOW` (
  `USER_ID` BIGINT NOT NULL,
  `FOLLOWING_ID` BIGINT NOT NULL,
  `FOLLOW_DATE` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `USER_FOLLOWED_FK_idx` (`FOLLOWING_ID` ASC) VISIBLE,
  INDEX `USER_FOLLOW_FK` (`USER_ID` ASC) VISIBLE,
  PRIMARY KEY (`USER_ID`, `FOLLOWING_ID`),
  CONSTRAINT `USER_FOLLOW_FK`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `chabit`.`USER` (`USER_ID`),
  CONSTRAINT `USER_FOLLOWED_FK`
    FOREIGN KEY (`FOLLOWING_ID`)
    REFERENCES `chabit`.`USER` (`USER_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chabit`.`LEVEL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chabit`.`LEVEL` ;

CREATE TABLE IF NOT EXISTS `chabit`.`LEVEL` (
  `LEVEL` VARCHAR(255) NOT NULL,
  `LEVEL_MIN_POINT` INT NOT NULL,
  `LEVEL_MAX_POINT` INT NOT NULL,
  PRIMARY KEY (`LEVEL`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chabit`.`POINT_HISTORY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chabit`.`POINT_HISTORY` ;

CREATE TABLE IF NOT EXISTS `chabit`.`POINT_HISTORY` (
  `HISTORY_ID` BIGINT NOT NULL,
  `USER_ID` BIGINT NULL DEFAULT NULL,
  `CHALLENGE_ID` BIGINT NULL DEFAULT NULL,
  `POINT_DATE` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `POINT_CHANGE` INT NOT NULL,
  PRIMARY KEY (`HISTORY_ID`),
  INDEX `POINT_HISTORY_USER_FK_idx` (`USER_ID` ASC) VISIBLE,
  INDEX `POINT_HISTORY_CHALLENGE_FK_idx` (`CHALLENGE_ID` ASC) VISIBLE,
  CONSTRAINT `POINT_HISTORY_CHALLENGE_FK`
    FOREIGN KEY (`CHALLENGE_ID`)
    REFERENCES `chabit`.`CHALLENGE` (`CHALLENGE_ID`),
  CONSTRAINT `POINT_HISTORY_USER_FK`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `chabit`.`USER` (`USER_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chabit`.`PROOF`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chabit`.`PROOF` ;

CREATE TABLE IF NOT EXISTS `chabit`.`PROOF` (
  `PROOF_ID` BIGINT NOT NULL,
  `USER_ID` BIGINT NULL DEFAULT NULL,
  `CHALLENGE_ID` BIGINT NULL DEFAULT NULL,
  `PROOF_DATE` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `PROOF_IMAGE` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`PROOF_ID`),
  INDEX `PROOF_USER_FK_idx` (`USER_ID` ASC) VISIBLE,
  INDEX `PROOF_CHALLENGE_FK_idx` (`CHALLENGE_ID` ASC) VISIBLE,
  CONSTRAINT `PROOF_CHALLENGE_FK`
    FOREIGN KEY (`CHALLENGE_ID`)
    REFERENCES `chabit`.`CHALLENGE` (`CHALLENGE_ID`),
  CONSTRAINT `PROOF_USER_FK`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `chabit`.`USER` (`USER_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chabit`.`REVIEW_COMMENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chabit`.`REVIEW_COMMENT` ;

CREATE TABLE IF NOT EXISTS `chabit`.`REVIEW_COMMENT` (
  `REVIEW_COMMENT_ID` BIGINT NOT NULL,
  `REVIEW_ID` BIGINT NULL DEFAULT NULL,
  `USER_ID` BIGINT NULL DEFAULT NULL,
  `COMMENT_CONTENT` TEXT NOT NULL,
  `PARENT_COMMENT_ID` BIGINT NULL DEFAULT NULL,
  `COMMENT_ORDER` INT NULL DEFAULT NULL,
  PRIMARY KEY (`REVIEW_COMMENT_ID`),
  INDEX `REVIEW_COMMENT_REVIEW_FK_idx` (`REVIEW_ID` ASC) VISIBLE,
  INDEX `REVIEW_COMMENT_USER_FK_idx` (`USER_ID` ASC) VISIBLE,
  INDEX `REVIEW_COMMENT_REVIEW_COMMENT_FK_idx` (`PARENT_COMMENT_ID` ASC) VISIBLE,
  CONSTRAINT `REVIEW_COMMENT_REVIEW_COMMENT_FK`
    FOREIGN KEY (`PARENT_COMMENT_ID`)
    REFERENCES `chabit`.`REVIEW_COMMENT` (`REVIEW_COMMENT_ID`),
  CONSTRAINT `REVIEW_COMMENT_REVIEW_FK`
    FOREIGN KEY (`REVIEW_ID`)
    REFERENCES `chabit`.`REVIEW` (`REVIEW_ID`),
  CONSTRAINT `REVIEW_COMMENT_USER_FK`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `chabit`.`USER` (`USER_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chabit`.`REVIEW_IMAGE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chabit`.`REVIEW_IMAGE` ;

CREATE TABLE IF NOT EXISTS `chabit`.`REVIEW_IMAGE` (
  `REVIEW_IMAGE_ID` BIGINT NOT NULL,
  `REVIEW_ID` BIGINT NULL DEFAULT NULL,
  `REVIEW_IMAGE` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`REVIEW_IMAGE_ID`),
  INDEX `REVIEW_IMAGE_REVIEW_FK_idx` (`REVIEW_ID` ASC) VISIBLE,
  CONSTRAINT `REVIEW_IMAGE_REVIEW_FK`
    FOREIGN KEY (`REVIEW_ID`)
    REFERENCES `chabit`.`REVIEW` (`REVIEW_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chabit`.`USER_CHALLENGE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chabit`.`USER_CHALLENGE` ;

CREATE TABLE IF NOT EXISTS `chabit`.`USER_CHALLENGE` (
  `USER_ID` BIGINT NOT NULL,
  `CHALLENGE_ID` BIGINT NOT NULL,
  `USER_CHALLENGE_RESULT` VARCHAR(45) NULL DEFAULT 'READY',
  INDEX `USER_CHALLNEGE_USER_FK_idx` (`USER_ID` ASC) VISIBLE,
  INDEX `USER_CHALLENGE_CHALLNEGE_FK_idx` (`CHALLENGE_ID` ASC) VISIBLE,
  PRIMARY KEY (`USER_ID`, `CHALLENGE_ID`),
  CONSTRAINT `USER_CHALLENGE_CHALLNEGE_FK`
    FOREIGN KEY (`CHALLENGE_ID`)
    REFERENCES `chabit`.`CHALLENGE` (`CHALLENGE_ID`),
  CONSTRAINT `USER_CHALLNEGE_USER_FK`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `chabit`.`USER` (`USER_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chabit`.`USER_HASHTAG`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chabit`.`USER_HASHTAG` ;

CREATE TABLE IF NOT EXISTS `chabit`.`USER_HASHTAG` (
  `USER_ID` BIGINT NOT NULL,
  `HASHTAG_ID` BIGINT NOT NULL,
  INDEX `USER_HASHTAG_USER_FK_idx` (`USER_ID` ASC) VISIBLE,
  INDEX `USER_HASHTAG_HASHTAG_FK_idx` (`HASHTAG_ID` ASC) VISIBLE,
  PRIMARY KEY (`USER_ID`, `HASHTAG_ID`),
  CONSTRAINT `USER_HASHTAG_HASHTAG_FK`
    FOREIGN KEY (`HASHTAG_ID`)
    REFERENCES `chabit`.`HASHTAG` (`HASHTAG_ID`),
  CONSTRAINT `USER_HASHTAG_USER_FK`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `chabit`.`USER` (`USER_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
